### PR TITLE
Little contribution from a Pythonista

### PR DESCRIPTION
**Pull request by davidfischer-ch**
I found your project and wanted to play with it.
Unfortunately I wasn't able to run your project with Python 2.7.
My goal is to make it Python 2.7 compatible and then script conversion to Python 3.4 using 2to3.
If I have time to do more I may improve quality of some functions.

Using Sublime Text 3 I saw many small PEP-8 warnings and I just fixed them (almost all).

Warning : I may have broken something, at least 1-50 works properly.

### CODE REVIEW

**Comment by dhermes** [comment]
Nice! I wrote this before I knew a whole lot.

How do you mean "modern" import? I realize now that asking people to add something to their `PYTHONPATH` was overkill, and I assume you're addressing this.

---

I started reviewing the PEP8 changes and it is a bit of a mouthful. Do you mind splitting them out into another PR? Also, I'd prefer to use an automated tool like `pep8ify` and just code review the script you used instead of the mountains of small changes.

**Comment by davidfischer-ch** [comment]
Hello,

I made it possible to use the python sources as a module named euler.
The benchmark tool still do some crazy imports magic but can be used directly.

I am sorry to say this but I don't have the energy to split this PR, so much modifications indeed.
However I added a little bounty, maybe it can make this PR more attractive :-)

I am open to any suggestions.

**Comment by dhermes** [comment]
@davidfischer-ch I peeled off the speedup for you and pushed to master. I'm going to address the PEP8 stuff myself.

Pretty amazing how simple the fix was to go from "too slow" (172 seconds) to plenty fast enough (1.04 seconds)!

**Comment by dhermes** [comment]
@davidfischer-ch I fixed all the PEP8 issues. If you like, you can re-implement your "modern import" fix. If you don't have time, no worries.

**Pull request closed without merging**
